services:
    Module\DemoDoctrine\Repository\QuoteRepository:
        public: true
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Module\DemoDoctrine\Entity\Quote

    Module\DemoDoctrine\Database\QuoteInstaller:
        public: true
        arguments:
            - '@doctrine.dbal.default_connection'
            - '%database_prefix%'
