imports:
    - { resource: ./common.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Module\DemoDoctrine\Controller\Admin\QuotesController: ~

    # Form services
    Module\DemoDoctrine\Form\QuoteType:
        parent: 'form.type.translatable.aware'
        arguments:
            - '@=service("prestashop.adapter.multistore_feature").isUsed()'
        tags:
            - { name: form.type }

    Module\DemoDoctrine\Form\QuoteFormDataProvider: ~

    prestashop.module.demodoctrine.form.identifiable_object.builder.quote_form_builder:
        class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Builder\FormBuilder'
        factory: [ '@prestashop.core.form.builder.form_builder_factory', 'create' ]
        arguments:
            - 'Module\DemoDoctrine\Form\QuoteType'
            - '@Module\DemoDoctrine\Form\QuoteFormDataProvider'

    Module\DemoDoctrine\Form\QuoteFormDataHandler: ~

    prestashop.module.demodoctrine.form.identifiable_object.handler.quote_form_handler:
        class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler'
        factory: [ '@prestashop.core.form.identifiable_object.handler.form_handler_factory', 'create' ]
        arguments:
            - '@Module\DemoDoctrine\Form\QuoteFormDataHandler'

    # Grid services
    prestashop.module.demodoctrine.grid.definition.factory.quotes:
        class: 'Module\DemoDoctrine\Grid\Definition\Factory\QuoteGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'

    Module\DemoDoctrine\Grid\Query\QuoteQueryBuilder:
        parent: 'prestashop.core.grid.abstract_query_builder'
        autowire: true
        autoconfigure: true

    prestashop.module.demodoctrine.grid.data_provider.quotes:
        class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
        arguments:
            - '@Module\DemoDoctrine\Grid\Query\QuoteQueryBuilder'
            - '@prestashop.core.hook.dispatcher'
            - '@prestashop.core.grid.query.doctrine_query_parser'
            - 'quote'

    prestashop.module.demodoctrine.grid.factory.quotes:
        class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
        arguments:
            - '@prestashop.module.demodoctrine.grid.definition.factory.quotes'
            - '@prestashop.module.demodoctrine.grid.data_provider.quotes'
            - '@prestashop.core.grid.filter.form_factory'
            - '@prestashop.core.hook.dispatcher'

    # Generator service
    Module\DemoDoctrine\Database\QuoteGenerator: ~
