# https://devdocs.prestashop.com/8/modules/concepts/services/
services:
    PrestaShop\Module\DemoProductForm\Form\Modifier\ProductFormModifier:
        autowire: true
        public: true
        arguments:
            $formBuilderModifier: '@form.form_builder_modifier'

    PrestaShop\Module\DemoProductForm\Form\Modifier\CombinationFormModifier:
        autowire: true
        public: true
        arguments:
            $formBuilderModifier: '@form.form_builder_modifier'

    PrestaShop\Module\DemoProductForm\CQRS\CommandHandler\UpdateCustomProductCommandHandler:
        class: PrestaShop\Module\DemoProductForm\CQRS\CommandHandler\UpdateCustomProductCommandHandler
        autoconfigure: true

    PrestaShop\Module\DemoProductForm\CQRS\CommandBuilder\CustomProductCommandsBuilder:
        class: PrestaShop\Module\DemoProductForm\CQRS\CommandBuilder\CustomProductCommandsBuilder
        # This tag is important. Core product command builder finds this builder by the tag
        tags: ['core.product_command_builder']

    PrestaShop\Module\DemoProductForm\Form\Type\CustomTabType:
        class: PrestaShop\Module\DemoProductForm\Form\Type\CustomTabType
        parent: 'form.type.translatable.aware'
        public: true
        arguments:
            - '@=service("prestashop.adapter.data_provider.currency").getDefaultCurrency()'
        tags:
            - { name: form.type }

    PrestaShop\Module\DemoProductForm\Form\Type\CustomTabContentType:
        class: PrestaShop\Module\DemoProductForm\Form\Type\CustomTabContentType
        parent: 'form.type.translatable.aware'
        public: true
        tags:
            - { name: form.type }
