services:
  Module\DemoGrid\Controller\Admin\IndexController:
    autoconfigure: true
    autowire: true

  # Grid services
  Module\DemoGrid\Grid\Definition\Factory\ProductGridDefinitionFactory:
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'

  Module\DemoGrid\Grid\Query\ProductQueryBuilder:
    parent: 'prestashop.core.grid.abstract_query_builder'
    autowire: true

  demo_grid.grid.data_provider.products:
    class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
    arguments:
      - '@Module\DemoGrid\Grid\Query\ProductQueryBuilder'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'product'

  demo_grid.grid.factory.products:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    public: true
    arguments:
      - '@Module\DemoGrid\Grid\Definition\Factory\ProductGridDefinitionFactory'
      - '@demo_grid.grid.data_provider.products'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'
