# https://devdocs.prestashop.com/8/modules/concepts/services/
services:
  # The decoration is defined thanks to the #[MapDecorated] attribute in the class itself
  PrestaShop\Module\DemoExtendTemplates\Controller\DecoratedOrderController:
    autowire: true
    autoconfigure: true
