services:
  _defaults:
    public: true

  democqrshooksusage.domain.reviewer.command_handler.toggle_is_allowed_to_review_handler:
    class: 'DemoCQRSHooksUsage\Domain\Reviewer\CommandHandler\ToggleIsAllowedToReviewHandler'
    autowire: true
    autoconfigure: true

  democqrshooksusage.domain.reviewer.query_handler.get_reviewer_settings_for_form_handler:
    class: 'DemoCQRSHooksUsage\Domain\Reviewer\QueryHandler\GetReviewerSettingsForFormHandler'
    autowire: true
    autoconfigure: true

  democqrshooksusage.domain.reviewer.command_handler.update_is_allowed_to_review_handler:
    class: 'DemoCQRSHooksUsage\Domain\Reviewer\CommandHandler\UpdateIsAllowedToReviewHandler'
    autowire: true
    autoconfigure: true
  
  DemoCQRSHooksUsage\Repository\ReviewerRepository:
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'
  democqrshooksusage.repository.reviewer:
    alias: DemoCQRSHooksUsage\Repository\ReviewerRepository

  DemoCQRSHooksUsage\Controller\Admin\CustomerReviewController:
    autowire: true
    autoconfigure: true
