services:
  _defaults:
    public: true
  PrestaShop\Module\DemoHowToExtendSymfonyForm\Repository\ReviewerRepository:
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'
  PrestaShop\Module\DemoHowToExtendSymfonyForm\Controller\Admin\CustomerReviewController:
    autoconfigure: true
    autowire: true
