services:
  _defaults:
    public: true

  PrestaShop\Module\DemoExtendSymfonyForm\Uploader\SupplierExtraImageUploader:
    autowire: true

  PrestaShop\Module\DemoExtendSymfonyForm\Repository\SupplierExtraImageRepository:
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments:
      - PrestaShop\Module\DemoExtendSymfonyForm\Entity\SupplierExtraImage

  PrestaShop\Module\DemoExtendSymfonyForm\Controller\DemoSupplierController:
    autowire: true
    autoconfigure: true

