admin_suppliers_delete_image:
  path: demosymfonyforms/{id}/delete-image
  methods: [POST]
  defaults:
    _controller: DemoSymfonyForms\Controller\DemoSupplierController:deleteSecondImageAction
  requirements:
    categoryId: \d+
