admin_suppliers_delete_image:
  path: demosymfonyforms/{id}/delete-image
  methods: [POST]
  defaults:
    _controller: PrestaShop\Module\DemoSymfonyForms\Controller\DemoSupplierController::deleteSecondImageAction
  requirements:
    categoryId: \d+
