services:
  _defaults:
    public: true

  PrestaShop\Module\ExampleModuleMailtheme\Controller\Admin\DarkThemeController:
    autoconfigure: true
    autowire: true

  PrestaShop\Module\ExampleModuleMailtheme\DarkThemeSettings:
    arguments:
      - '@prestashop.adapter.legacy.configuration'
      - "@=service('prestashop.adapter.legacy.context').getLanguages()"

  PrestaShop\Module\ExampleModuleMailtheme\Form\DarkThemeSettingsType:
    public: true
    parent: 'form.type.translatable.aware'
    tags:
      - { name: form.type }
