<?php
/**
 * Copyright since 2007 PrestaShop SA and Contributors
 * PrestaShop is an International Registered Trademark & Property of PrestaShop SA
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License version 3.0
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/AFL-3.0
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@prestashop.com so we can send you a copy immediately.
 *
 * @author    PrestaShop SA and Contributors <contact@prestashop.com>
 * @copyright Since 2007 PrestaShop SA and Contributors
 * @license   https://opensource.org/licenses/AFL-3.0 Academic Free License version 3.0
 */

namespace PrestaShop\Module\DemoProductForm\Entity;

/**
 * Example object model for module custom product fields
 */
final class CustomProduct extends \ObjectModel
{
    /** @var int Object ID */
    public $id;

    public string $custom_field = '';

    public float $custom_price = 0.0;

    public string $date_add;

    public string $date_upd;

    // forces the id to be set before saving object (because we don't need autogenerated id for this model)
    /** @var bool Enables to define an ID before adding object. */
    public $force_id = true;

    public static $definition = [
        'table' => 'demoproductform_custom_product',
        'primary' => 'id',
        'fields' => [
            'custom_field' => ['type' => self::TYPE_STRING],
            'custom_price' => ['type' => self::TYPE_FLOAT, 'validate' => 'isPrice'],
            'date_add' => ['type' => self::TYPE_DATE, 'validate' => 'isDate'],
            'date_upd' => ['type' => self::TYPE_DATE, 'validate' => 'isDate'],
        ],
    ];
}
